[package]
name = "rackio-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "rackio_desktop"

[[bin]]
name = "rackio-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
directories.workspace = true
qrcode.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-notification.workspace = true
tempfile.workspace = true
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
rackio-windows-ipc = { version = "0.1.0", path = "../../../crates/rackio-windows-ipc" }

[lints]
workspace = true
