[package]
name = "rackio-iroh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
iroh.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
swarm-discovery.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
rackio-core = { version = "0.1.0", path = "../rackio-core" }
rackio-protocol = { version = "0.1.0", path = "../rackio-protocol" }
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
